name: Buld and TEst

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkoot repo
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Run unit tests 
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo 'dragolub'

  run_ui_tests:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkoot repo
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Istall Playwright browsers
      run: npx playwright install  
    - name: Start the app
      run: npm run start &  
    - name: Run The UI tests 
      run: npm run test:ui
  
  deploy:
    needs: run_ui_tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          